"""add address column to seller

Revision ID: 0832feafa9dc
Revises: db68da232864
Create Date: 2026-04-07 21:20:40.767898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0832feafa9dc'
down_revision: Union[str, Sequence[str], None] = 'db68da232864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'address')
    # ### end Alembic commands ###
