"""Add Tag

Revision ID: 13a024e55eca
Revises: 5e88cff9918f
Create Date: 2026-04-11 23:07:11.639354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "13a024e55eca"
down_revision: Union[str, Sequence[str], None] = "5e88cff9918f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "EXPRESS",
                "STANDARD",
                "FRAGILE",
                "HEAVY",
                "INTERNATIONAL",
                "DOMESTIC",
                "TEMPERATURE_CONTROLLED",
                "GIFT",
                "RETURN",
                "DOCUMENTS",
                name="tagname",
            ),
            nullable=False,
        ),
        sa.Column("instruction", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment_tags",
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("shipment_id", "tag_id"),
    )
    # ### end Alembic commands ###
    import uuid
    from app.database.models import TagName

    tags_data = [
        {
            "id": uuid.uuid4(),
            "name": TagName.EXPRESS,
            "instruction": "Handle with high priority for fast delivery.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.STANDARD,
            "instruction": "Standard handling and delivery procedures.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.FRAGILE,
            "instruction": "Handle with care to prevent breakage.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.HEAVY,
            "instruction": "Requires two people or mechanical assistance for lifting.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.INTERNATIONAL,
            "instruction": "Ensure all customs documentation is present.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.DOMESTIC,
            "instruction": "Process according to local shipping regulations.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.TEMPERATURE_CONTROLLED,
            "instruction": "Keep within specified temperature range at all times.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.GIFT,
            "instruction": "Ensure gift wrap is intact and remove price tags if possible.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.RETURN,
            "instruction": "Process as a returned item and inspect for damages.",
        },
        {
            "id": uuid.uuid4(),
            "name": TagName.DOCUMENTS,
            "instruction": "Handle as sensitive documentation, ensure no folding.",
        },
    ]

    for tag in tags_data:
        op.execute(
            sa.text(
                "INSERT INTO tags (id, name, instruction) VALUES (:id, CAST(:name AS tagname), :instruction)"
            ).bindparams(
                id=tag["id"],
                name=tag["name"],
                instruction=tag["instruction"],
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
