"""change shipment client phone data type

Revision ID: 2e01312ac7f7
Revises: bfc884d140e7
Create Date: 2026-04-11 11:20:43.656524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e01312ac7f7'
down_revision: Union[str, Sequence[str], None] = 'bfc884d140e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.BIGINT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
