"""Shipment contact phone field update

Revision ID: 6fd850826484
Revises: cfb19c11bb38
Create Date: 2026-04-10 18:50:56.435692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fd850826484'
down_revision: Union[str, Sequence[str], None] = 'cfb19c11bb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
