"""Shipment Events

Revision ID: bb8bf9017c35
Revises: 9c19ce46f18b
Create Date: 2026-04-09 00:06:13.276276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bb8bf9017c35'
down_revision: Union[str, Sequence[str], None] = '9c19ce46f18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sellers', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.add_column('shipment_events', sa.Column('location', sa.Integer(), nullable=False))
    op.add_column('shipment_events', sa.Column('status', sa.Enum('placed', 'in_transit', 'delivered', 'out_for_delivery', name='shipmentstatus'), nullable=False))
    op.add_column('shipment_events', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment_events', sa.Column('shipment_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment_events', 'shipments', ['shipment_id'], ['id'])
    op.drop_column('shipments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'delivered', 'out_for_delivery', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shipment_events', type_='foreignkey')
    op.drop_column('shipment_events', 'shipment_id')
    op.drop_column('shipment_events', 'description')
    op.drop_column('shipment_events', 'status')
    op.drop_column('shipment_events', 'location')
    op.drop_column('sellers', 'zip_code')
    op.drop_column('sellers', 'address')
    # ### end Alembic commands ###
