"""User email verified field addition

Revision ID: bfc884d140e7
Revises: 6fd850826484
Create Date: 2026-04-10 21:24:06.542947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfc884d140e7'
down_revision: Union[str, Sequence[str], None] = '6fd850826484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partners', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('sellers', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'email_verified')
    op.drop_column('delivery_partners', 'email_verified')
    # ### end Alembic commands ###
