"""Shipment contact fields

Revision ID: cfb19c11bb38
Revises: 131eabff66b2
Create Date: 2026-04-10 18:41:15.834152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfb19c11bb38'
down_revision: Union[str, Sequence[str], None] = '131eabff66b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipments', sa.Column('client_contact_phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'client_contact_phone')
    op.drop_column('shipments', 'client_contact_email')
    # ### end Alembic commands ###
